OM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Bauprojekt/Bauprojekt.csproj", "Bauprojekt/"]
RUN dotnet restore "Bauprojekt/Bauprojekt.csproj"
COPY . .
WORKDIR "/src/Bauprojekt"
RUN dotnet build "Bauprojekt.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Bauprojekt.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Bauprojekt.dll"]
